In [1]:
import pandas as pd

In [2]:
datas = pd.read_html('https://fr.countryeconomy.com/energie-et-environnement/electricite-consommation/madagascar')[0]
datas

    Date  Production GWh  Consommation GWh  Consommation par habitant kWh
0   2021           2.093             1.956                            676
1   2020           1.976             1.862                            660
2   2019           2.020             1.889                            686
3   2018           2.271             2.166                            844
4   2017           2.211             2.101                            842
5   2016           2.024             1.916                            792
6   2015           2.052             1.949                            829
7   2014           1.970             1.873                            821
8   2013           1.856             1.762                            795
9   2012           1.701             1.617                            752
10  2011           1.348             1.271                            609
11  2010           1.329             1.260                            622
12  2009           1.235             1.173                            596
13  2008           1.232             1.182                            619
14  2007           1.184             1.131                            610
15  2006           1.134             1.089                            605
16  2005           1.111             1.064                            609
17  2004           1.100             1.054                            622
18  2003         990.000           945.000                            574
19  2002         866.000           827.000                            517
20  2001         886.000           848.000                            547
21  2000         780.000           747.000                            496
22  1999         777.000           723.000                            494
23  1998         750.000           698.000                            491
24  1997         695.000           646.000                            469
25  1996         664.000           618.000                            462
26  1995         609.000           566.000                            436
27  1994         584.000           543.000                            431
28  1993         581.000           540.000                            442
29  1992         580.000           539.000                            453
30  1991         568.000           528.000                            455
31  1990         574.000           534.000                            472
32  1989         541.000           503.000                            457
33  1988         490.000           456.000                            425
34  1987         478.000           445.000                            426
35  1986         482.000           448.000                            441
36  1985         483.000           449.000                            454
37  1984         476.000           443.000                            459
38  1983         452.000           420.000                            447
39  1982         431.000           401.000                            438
40  1981         420.000           391.000                            438
41  1980         417.000           388.000                            447

In [3]:
datas = datas.sort_values(by='Date', ascending=True)
datas = datas.reset_index(drop=True)
datas

    Date  Production GWh  Consommation GWh  Consommation par habitant kWh
0   1980         417.000           388.000                            447
1   1981         420.000           391.000                            438
2   1982         431.000           401.000                            438
3   1983         452.000           420.000                            447
4   1984         476.000           443.000                            459
5   1985         483.000           449.000                            454
6   1986         482.000           448.000                            441
7   1987         478.000           445.000                            426
8   1988         490.000           456.000                            425
9   1989         541.000           503.000                            457
10  1990         574.000           534.000                            472
11  1991         568.000           528.000                            455
12  1992         580.000           539.000                            453
13  1993         581.000           540.000                            442
14  1994         584.000           543.000                            431
15  1995         609.000           566.000                            436
16  1996         664.000           618.000                            462
17  1997         695.000           646.000                            469
18  1998         750.000           698.000                            491
19  1999         777.000           723.000                            494
20  2000         780.000           747.000                            496
21  2001         886.000           848.000                            547
22  2002         866.000           827.000                            517
23  2003         990.000           945.000                            574
24  2004           1.100             1.054                            622
25  2005           1.111             1.064                            609
26  2006           1.134             1.089                            605
27  2007           1.184             1.131                            610
28  2008           1.232             1.182                            619
29  2009           1.235             1.173                            596
30  2010           1.329             1.260                            622
31  2011           1.348             1.271                            609
32  2012           1.701             1.617                            752
33  2013           1.856             1.762                            795
34  2014           1.970             1.873                            821
35  2015           2.052             1.949                            829
36  2016           2.024             1.916                            792
37  2017           2.211             2.101                            842
38  2018           2.271             2.166                            844
39  2019           2.020             1.889                            686
40  2020           1.976             1.862                            660
41  2021           2.093             1.956                            676

In [4]:
datas.to_csv('prod_conso_energy.csv', index=False)